-- Import Google Form responses → client_details.form_data + phone/birthday
-- Also: profiles.email and profiles.phone
-- Run AFTER schema.sql + all migrations (0001-0009).
-- Safe to re-run: each UPDATE overwrites for the matched client.

-- SKIPPED (no profile match): 'James Monroe'
-- Ryan Mecca → manually applied 2026-05-11 (was admin at import time; profile_id 00000000-0000-0000-0000-000000000ad1)
UPDATE profiles SET phone = '(706)573-8225' WHERE id = '00000000-0000-0000-0000-000000000ad1';
UPDATE client_details
  SET birthday = '1999-03-06',
      starting_weight_lb = 120,
      current_weight_lb = 124,
      form_data = '{"Phone": "(706)573-8225", "Birthday": "1999-03-06", "Training goals": "Lose body fat, Gain strength, Gain range of motion, Balance, return to running/reduce pain, handstand, swim 1 mile", "Primary goal / motivation": "my body is a gift and I want to honor it; I want to feel functional and increase confidence", "Strengths / most improved": "confident in form for many exercises", "Needs most improvement": "knowing limitations and scaling effectively (when to add and when to take away)", "Satisfaction with training (1-5)": "5", "Exercises to learn / work on": "compound lifts, mobility training", "Nutrition confidence (1-5)": "4", "Height": "5''4", "Starting weight (lbs)": "120", "Current weight (lbs)": "124", "Sessions per month (preferred)": "4", "Available days": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", "Available times": "Midday, Afternoon, Evening", "Ideal session times": "Monday 3 PM, Tuesday 3 PM, Thursday 3 PM", "Additional requests / notes": "inconsistent work schedule", "Time frame": "3 months", "Questions / feedback": "You''re doing a great job and I''m proud of you (:", "Activity level outside training (1-5)": "4", "Self-exercise days per week": "4", "Nutrition tracking": "2100 cal target, high protein, mostly whole foods", "Sleep / recovery (1-5)": "4", "Preferred coaching style": "Direct, supportive, scientific", "Past consistency barriers": "injury, lack of recovery", "Commitment (1-10)": "10", "Injuries / limitations": "knees (primarily left knee), right shoulder is hiked"}'::jsonb,
      form_received_at = '2026-05-04T11:51:56Z'
  WHERE profile_id = '00000000-0000-0000-0000-000000000ad1';

-- Isabella Rowland → Rowland Bella
UPDATE profiles SET email = 'isabellarowland133@gmail.com', phone = '5127500805' WHERE full_name = 'Rowland Bella' AND email IS NULL;
UPDATE client_details
  SET birthday = '2001-11-25',
      form_data = '{"Phone": "5127500805", "Birthday": "2001-11-25", "Training goals": "Lose body fat, Gain strength, Learn about nutrition, Gain range of motion, Balance, Cardiovascular health", "Strengths / most improved": "Clothes and scale and food", "Needs most improvement": "Steps", "Satisfaction with training (1-5)": "4", "Exercises to learn / work on": "Maybe more motion type workouts, like instead of rows and squats, just more movement maybe? But I dunno about running.", "Nutrition confidence (1-5)": "4", "Height": "5’11.2”", "Starting weight (lbs)": "433 from what I remember", "Current weight (lbs)": "294", "Sessions per month (preferred)": "8", "Available days": "Tuesday, Thursday", "Available times": "Evening", "Ideal session times": "Our usual times", "Activity level outside training (1-5)": "3", "Self-exercise days per week": "1", "Nutrition tracking": "Yes I’m tracking", "Sleep / recovery (1-5)": "3", "Preferred coaching style": "I like the positive outlook that you have on our training.", "Past consistency barriers": "Motivation", "Commitment (1-10)": "9", "Injuries / limitations": "I have that knee that buckles sometimes, I have pcos that you know about and I also have acid reflux attacks at times too."}'::jsonb,
      form_received_at = '2026-05-04T12:15:21Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Rowland Bella' LIMIT 1);

-- Ragnar Rowland → Rowland Ragnar
UPDATE profiles SET email = 'r.s.rowland@sbcglobal.net', phone = '5127862693' WHERE full_name = 'Rowland Ragnar' AND email IS NULL;
UPDATE client_details
  SET birthday = '1975-10-01',
      form_data = '{"Phone": "5127862693", "Birthday": "1975-10-01", "Training goals": "Lose body fat, Gain strength, Learn about nutrition, Gain range of motion, Balance, Cardiovascular health", "Primary goal / motivation": "Get to a healthy weight get rid of all of not most of both diabetes meds and blood pressure meds. Also increase agility and balance", "Strengths / most improved": "Beginning to lose weight, but slower than what I was.", "Needs most improvement": "Revisit some of the core exercises", "Satisfaction with training (1-5)": "5", "Exercises to learn / work on": "More core strengthening and balance.", "Nutrition confidence (1-5)": "4", "Height": "5 ft 10 in", "Starting weight (lbs)": "352", "Current weight (lbs)": "332", "Sessions per month (preferred)": "I like what we are doing now. Me and Bella 1 and Jen and Bella 1. I would like to may be add 1 a month 1:1", "Available days": "Monday, Tuesday, Wednesday", "Available times": "Evening", "Ideal session times": "Tuesday 6pm, Monday 6pm, Wednesday 6pm", "Additional requests / notes": "Just the lower back and hip pain, along with the leg pain. Desire to improve gait", "Time frame": "?", "Questions / feedback": "I appreciate your guidance, coaching, availability and flexibility", "Activity level outside training (1-5)": "3", "Self-exercise days per week": "1", "Nutrition tracking": "Yes, loose it app", "Sleep / recovery (1-5)": "3", "Preferred coaching style": "What you are doing, highlighting and celebrating the successes and giving corrective measures and feedback.", "Past consistency barriers": "Time management. Deadlines, stress.", "Commitment (1-10)": "8", "Injuries / limitations": "Knees, foot drop, hip and lower back pain"}'::jsonb,
      form_received_at = '2026-05-04T12:35:03Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Rowland Ragnar' LIMIT 1);

-- Samantha Saenz → Samantha Saenz
UPDATE profiles SET email = 'sdanell512@gmail.com', phone = '956-457-1129' WHERE full_name = 'Samantha Saenz' AND email IS NULL;
UPDATE client_details
  SET birthday = '2000-02-05',
      form_data = '{"Phone": "956-457-1129", "Birthday": "2000-02-05", "Training goals": "Lose body fat, Gain strength, Gain range of motion, Balance", "Primary goal / motivation": "I''ve been losing weight (goal is 140 lbs) and changing my lifestyle for over a year now and the thing that keeps me motivated is seeing the shift in my abilities and building my self-confidence.", "Strengths / most improved": "Being active, self image, nutrition, and the scale", "Needs most improvement": "Creating new routines, branching out in movements and exercises", "Satisfaction with training (1-5)": "5", "Exercises to learn / work on": "Pull ups hehe, generally just being able to manipulate my own body more", "Nutrition confidence (1-5)": "4", "Height": "5''2", "Starting weight (lbs)": "Initially at 24H, 188 lbs. Most recent start at 148 lbs", "Current weight (lbs)": "147", "Sessions per month (preferred)": "2-4", "Available days": "Monday, Friday", "Available times": "Morning, Midday, Afternoon", "Ideal session times": "Monday early afternoon, Friday late morning or afternoon", "Additional requests / notes": "Just that my schedule can be tricky to manage. I also have trips coming up that may make it difficult to meet but I''ll communicate those.", "Questions / feedback": "If you had to put a timeframe on my goals and growth, how long do you anticipate it would take for me to meet my goals? I appreciate working with you, especially the humor and just genuineness during our sessions. It makes training fun and keeps me motivated.", "Activity level outside training (1-5)": "3", "Self-exercise days per week": "3", "Nutrition tracking": "Nutritionist and I''m using My Net Diary for meal tracking", "Sleep / recovery (1-5)": "3", "Preferred coaching style": "Realistic and straightforward.", "Past consistency barriers": "Time and other responsibilities/obligations", "Commitment (1-10)": "10", "Injuries / limitations": "No"}'::jsonb,
      form_received_at = '2026-05-04T12:36:43Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Samantha Saenz' LIMIT 1);

-- Kathryn Sheppard → Katherine Sheppard
UPDATE profiles SET email = 'kathrynmsheppard17@gmail.com', phone = '5127622504' WHERE full_name = 'Katherine Sheppard' AND email IS NULL;
UPDATE client_details
  SET birthday = '1995-05-04',
      form_data = '{"Phone": "5127622504", "Birthday": "1995-05-04", "Training goals": "Lose body fat, Gain strength, Learn about nutrition, Gain range of motion, Cardiovascular health", "Strengths / most improved": "Training with James and developing a routine that I can easily do outside of training sessions.", "Needs most improvement": "Maybe food tracking — lately I haven’t been writing it/logging it in, but my portions have been fine.", "Satisfaction with training (1-5)": "5", "Nutrition confidence (1-5)": "3", "Height": "6 ft", "Starting weight (lbs)": "314", "Current weight (lbs)": "284", "Sessions per month (preferred)": "4 (once a week)", "Available days": "Monday, Wednesday", "Available times": "Evening", "Ideal session times": "Wednesdays @ 6, Mondays at 6, Fridays at 6", "Activity level outside training (1-5)": "4", "Self-exercise days per week": "3", "Nutrition tracking": "Yes tracking using Fitbit", "Sleep / recovery (1-5)": "4", "Past consistency barriers": "Stress, time management, my job", "Commitment (1-10)": "8", "Injuries / limitations": "No"}'::jsonb,
      form_received_at = '2026-05-04T12:46:40Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Katherine Sheppard' LIMIT 1);

-- Keaton Ley → Keaton Ley
UPDATE profiles SET email = 'Leyk96@gmail.com', phone = '9794170776' WHERE full_name = 'Keaton Ley' AND email IS NULL;
UPDATE client_details
  SET birthday = '1996-11-03',
      form_data = '{"Phone": "9794170776", "Birthday": "1996-11-03", "Training goals": "Lose body fat, Gain strength", "Primary goal / motivation": "Get stronger, leaner (less body fat %), protect family", "Strengths / most improved": "Arms", "Needs most improvement": "Core and shoulders", "Satisfaction with training (1-5)": "5", "Nutrition confidence (1-5)": "4", "Height": "6’0", "Starting weight (lbs)": "187", "Current weight (lbs)": "180", "Sessions per month (preferred)": "4", "Available days": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday", "Available times": "Morning, Midday", "Ideal session times": "Thursday Friday Saturday late morning", "Activity level outside training (1-5)": "3", "Self-exercise days per week": "3", "Nutrition tracking": "Tracking protein, calories and fats", "Sleep / recovery (1-5)": "4", "Past consistency barriers": "Lack of motivation", "Commitment (1-10)": "10", "Injuries / limitations": "No"}'::jsonb,
      form_received_at = '2026-05-04T13:11:34Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Keaton Ley' LIMIT 1);

-- Hahn → Hahn Franklin
UPDATE profiles SET email = 'Hgfm42@gmail.com', phone = '4697664649' WHERE full_name = 'Hahn Franklin' AND email IS NULL;
UPDATE client_details
  SET birthday = '1989-03-06',
      form_data = '{"Phone": "4697664649", "Birthday": "1989-03-06", "Training goals": "Lose body fat, Gain strength, Cardiovascular health", "Satisfaction with training (1-5)": "4", "Nutrition confidence (1-5)": "4", "Height": "6’1", "Starting weight (lbs)": "220", "Current weight (lbs)": "215", "Sessions per month (preferred)": "9", "Available days": "Monday, Tuesday, Wednesday, Thursday, Friday", "Available times": "Morning, Midday, Afternoon, Evening", "Ideal session times": "5 pm Monday Wednesday whenever on Friday", "Activity level outside training (1-5)": "3", "Self-exercise days per week": "3", "Nutrition tracking": "No", "Sleep / recovery (1-5)": "3", "Commitment (1-10)": "8", "Injuries / limitations": "No"}'::jsonb,
      form_received_at = '2026-05-04T15:43:30Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Hahn Franklin' LIMIT 1);

-- Nick Daniels → Nick Daniels
UPDATE profiles SET email = 'Nicholasidaniels@gmail.com', phone = '5132576680' WHERE full_name = 'Nick Daniels' AND email IS NULL;
UPDATE client_details
  SET birthday = '1993-05-11',
      form_data = '{"Phone": "5132576680", "Birthday": "1993-05-11", "Training goals": "Lose body fat, Gain strength, Learn about nutrition, Gain range of motion", "Primary goal / motivation": "Primary goal: Trim down the body fat to be in a more healthy range for age/height; and then secondary is to simultaneously build overall muscle strength to toned “look” along with improving cardio endurance.", "Strengths / most improved": "I’ve seen the most improvement in my endurance (cardio) and in my overall health habits outside the gym through our calorie and protein intake conversations.", "Needs most improvement": "I’d say with upper body strength and with cardio for longer duration/HIIT\n\nJust staying locked in on the mission. Always appreciate the tap ins via text when I have delays getting to our sessions when I’m out of town", "Satisfaction with training (1-5)": "5", "Exercises to learn / work on": "Core. Cardio. Upper Body.", "Nutrition confidence (1-5)": "4", "Height": "5’10", "Starting weight (lbs)": "224", "Current weight (lbs)": "182", "Sessions per month (preferred)": "4", "Available days": "Tuesday, Thursday, Friday, Saturday", "Available times": "Afternoon, Evening", "Ideal session times": "Thursday (Afternoon/Evening). Friday (Noon-Early Afternoon). Saturday (11a-3p)", "Additional requests / notes": "Just pushing past each limit. \n\nWould like to start maybe introducing a rotation of 1-2 workouts into what we normally (resistance, cardio, etc) do and keeping tally’s of where we were with sets, distance, etc and seeing where we can challenge to push past them.", "Activity level outside training (1-5)": "4", "Self-exercise days per week": "2", "Nutrition tracking": "Yes. I’m tracking caloric intake. Sticking to roughly 1500 or less calories a day while maintaining a min of 120+ Protein a day, while pushing for 150+ when possible.", "Sleep / recovery (1-5)": "3", "Preferred coaching style": "Challenging and pushing. Even when I know there’s stakes on the line or a camera on I know I gotta push that much harder, when I know I gotta go one more punch, one more toss, throw it out there to get to 20 instead of stopping with that stop watch at 17, that type of push past your limits see what you can do. I love that type.\n\nAlso like I said before the check ins and just making sure in staying on course with my own routines and weight loss outside of what we do is hella motivation as well", "Past consistency barriers": "Work. With my work being a lot of travel with long days (12-16 hour work days on festival sites) with no days off for 2-3 weeks off at a time it can be disruptive to consistency and rhythm. And then restarting that rhythm.", "Commitment (1-10)": "10", "Injuries / limitations": "Right shoulder - sore/range of motion from an accident."}'::jsonb,
      form_received_at = '2026-05-04T16:57:34Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Nick Daniels' LIMIT 1);

-- Jennifer Rowland → Jen Rowland
UPDATE profiles SET email = 'jrowland319@gmail.com', phone = '5127969261' WHERE full_name = 'Jen Rowland' AND email IS NULL;
UPDATE client_details
  SET birthday = '1971-03-19',
      form_data = '{"Phone": "5127969261", "Birthday": "1971-03-19", "Training goals": "Lose body fat, Gain strength", "Primary goal / motivation": "Want to get healthy to where I can get off of my medication", "Strengths / most improved": "In my upper body strength", "Needs most improvement": "Legs, hips and thighs", "Satisfaction with training (1-5)": "4", "Exercises to learn / work on": "More all over body stuff", "Nutrition confidence (1-5)": "3", "Height": "5’11”", "Starting weight (lbs)": "408", "Current weight (lbs)": "385", "Sessions per month (preferred)": "4", "Available days": "Tuesday, Thursday", "Available times": "Evening", "Ideal session times": "Thursdays at 6", "Additional requests / notes": "No", "Time frame": "Nope - love training", "Questions / feedback": "No", "Activity level outside training (1-5)": "3", "Self-exercise days per week": "0", "Nutrition tracking": "High protein macros", "Sleep / recovery (1-5)": "2", "Preferred coaching style": "What you are doing", "Past consistency barriers": "Myself, lack of consistency", "Commitment (1-10)": "8", "Injuries / limitations": "Ankle and right wrist"}'::jsonb,
      form_received_at = '2026-05-04T22:01:41Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Jen Rowland' LIMIT 1);

-- Katherine Serradell → Katherine Serredel
UPDATE profiles SET email = 'kathye.dell23@gmail.com', phone = '(956)285-2645' WHERE full_name = 'Katherine Serredel' AND email IS NULL;
UPDATE client_details
  SET birthday = '2000-06-08',
      form_data = '{"Phone": "(956)285-2645", "Birthday": "2000-06-08", "Training goals": "Gain strength, Gain range of motion, Balance, Cardiovascular health", "Primary goal / motivation": "By the end of this year I want to be able to do a pull up and be able to do at least 10 push ups. I just want basic body strength and endurance.", "Strengths / most improved": "I think when it comes to boxing my endurance has increased a lot (which I really like because I generally hate cardio so I never do it). My strength has also definitely increased since starting sessions, but I think I’ve stagnated over the past few months due to work.", "Needs most improvement": "I think I need a weekly strength training plan to follow outside of our sessions and would really like to work on more mobility & balance exercises (because i started ice skating recently and balancing on one foot on ice is hard haha).", "Satisfaction with training (1-5)": "5", "Exercises to learn / work on": "pull up, push up, balance exercises", "Nutrition confidence (1-5)": "3", "Height": "5’1", "Starting weight (lbs)": "(i have no idea tbh i never measured and don’t own a scale) but i think ~130lbs", "Current weight (lbs)": "i think i’m still around 130lbs? (not sure tho)", "Sessions per month (preferred)": "once a week (so 4-5 a month)", "Available days": "Saturday, Sunday", "Available times": "Morning", "Ideal session times": "Our current time on Saturdays at 10am is still ideal atm, but once I leave my job around the end of June, I would prefer to meet on a weekday in the afternoon or midday (just not sure which day of the week yet).", "Additional requests / notes": "I think we’ve discussed this before but training agility to be fast on my feet (I think you mentioned floor ladders once?).", "Time frame": "Ideally 10 pushups by the end of September and 1 pull up by the end of the year (i’m just not as optimistic with my pulls ups).", "Questions / feedback": "none", "Activity level outside training (1-5)": "1", "Self-exercise days per week": "1", "Nutrition tracking": "No", "Sleep / recovery (1-5)": "5", "Preferred coaching style": "pushing me to continue when i’m tired hahaha", "Past consistency barriers": "my job lol (or traveling)", "Commitment (1-10)": "9", "Injuries / limitations": "occasional pain on right knee"}'::jsonb,
      form_received_at = '2026-05-05T10:33:01Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Katherine Serredel' LIMIT 1);

-- Jim Darling → Jim Darling
UPDATE profiles SET email = 'jimdarling1@gmail.com', phone = '5127407246' WHERE full_name = 'Jim Darling' AND email IS NULL;
UPDATE client_details
  SET birthday = '2026-07-29',
      form_data = '{"Phone": "5127407246", "Birthday": "2026-07-29", "Training goals": "Gain strength", "Strengths / most improved": "Chest", "Needs most improvement": "Abs", "Satisfaction with training (1-5)": "5", "Nutrition confidence (1-5)": "5", "Height": "5’8”", "Starting weight (lbs)": "170", "Current weight (lbs)": "160", "Sessions per month (preferred)": "4-5 Weekly", "Available days": "Thursday", "Available times": "Morning", "Ideal session times": "Thursday~8am/rest of the week depends on schedule", "Additional requests / notes": "Would like to see my abs one day maybe also be able to do a pull-up", "Activity level outside training (1-5)": "5", "Self-exercise days per week": "2", "Nutrition tracking": "Both~pescatarian", "Sleep / recovery (1-5)": "4", "Past consistency barriers": "Time", "Commitment (1-10)": "8", "Injuries / limitations": "No"}'::jsonb,
      form_received_at = '2026-05-06T20:37:37Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Jim Darling' LIMIT 1);

-- Sairam Jaishankar → Sairam Jaisankar
UPDATE profiles SET email = 'sairam.jaishankar@gmail.com', phone = '4049169019' WHERE full_name = 'Sairam Jaisankar' AND email IS NULL;
UPDATE client_details
  SET birthday = '1997-12-15',
      form_data = '{"Phone": "4049169019", "Birthday": "1997-12-15", "Training goals": "Gain strength, Learn about nutrition, Gain range of motion, Cardiovascular health, Gain weight", "Primary goal / motivation": "To achieve a bmi > 20, increase strength, cardio, and range of motion", "Strengths / most improved": "Almost 20-25lb weight gain since Sep 2025, better physique and strength, clothes fit better", "Needs most improvement": "A little motivation to help get past the diet stagnation", "Satisfaction with training (1-5)": "5", "Nutrition confidence (1-5)": "4", "Height": "5''7", "Starting weight (lbs)": "96", "Current weight (lbs)": "120", "Sessions per month (preferred)": "Currently 4/5, hopefully more in the later half of the year", "Available days": "Saturday", "Available times": "Midday, Afternoon", "Ideal session times": "Sat 1/2 pm", "Activity level outside training (1-5)": "3", "Self-exercise days per week": "2", "Nutrition tracking": "Yes", "Sleep / recovery (1-5)": "4", "Preferred coaching style": "Positive feedback/reinforcement, helping push to near limit", "Past consistency barriers": "Occasional lethargy to workout outside of training sessions, varying work schedule affecting meal times", "Commitment (1-10)": "10", "Injuries / limitations": "No"}'::jsonb,
      form_received_at = '2026-05-06T20:42:08Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Sairam Jaisankar' LIMIT 1);

-- SKIPPED (no profile match): 'Seamus Bradnan'
-- ^ Submitted as 'Seamus Bradnan'; profile is 'Seamus Ley'. Link manually if needed.
-- Jesse Ramazani → Jesse Ramanazi
UPDATE profiles SET email = 'jesseramazani@gmail.com', phone = '(512)975-6433' WHERE full_name = 'Jesse Ramanazi' AND email IS NULL;
UPDATE client_details
  SET birthday = '1981-10-26',
      form_data = '{"Phone": "(512)975-6433", "Birthday": "1981-10-26", "Training goals": "Lose body fat, Hypertrophy", "Primary goal / motivation": "Build muscle size and definition", "Strengths / most improved": "Weight loss", "Needs most improvement": "Avoiding injury", "Satisfaction with training (1-5)": "5", "Nutrition confidence (1-5)": "5", "Height": "5’ 11”", "Starting weight (lbs)": "185", "Current weight (lbs)": "151", "Sessions per month (preferred)": "4", "Available days": "Monday, Sunday", "Available times": "Midday, Afternoon, Evening", "Ideal session times": "Monday or sunday", "Activity level outside training (1-5)": "4", "Self-exercise days per week": "4", "Nutrition tracking": "Counting calories", "Sleep / recovery (1-5)": "2", "Past consistency barriers": "Never worked out in the past", "Commitment (1-10)": "10", "Injuries / limitations": "Wrist damage from previous injury, elbow injury"}'::jsonb,
      form_received_at = '2026-05-10T10:37:41Z'
  WHERE profile_id = (SELECT id FROM profiles WHERE full_name = 'Jesse Ramanazi' LIMIT 1);
